# Generated by Django 5.2.5 on 2025-10-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventattendance_delete_eventvote_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventattendance',
            index=models.Index(fields=['event', 'user'], name='core_eventa_event_i_79d85f_idx'),
        ),
    ]
