# Generated by Django 5.2.5 on 2025-11-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_eventattendance_core_eventa_event_i_79d85f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_token',
            field=models.CharField(blank=True, help_text='出席用QRコードに埋め込むトークン', max_length=32, null=True, unique=True),
        ),
    ]
