# Generated by Django 5.2.5 on 2026-01-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendance',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='QRコードで出席記録した時間', null=True),
        ),
    ]
