# Generated by Codex on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_eventattendance_checked_in_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="experience_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="faculty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("humanities", "人文社会科学部"),
                    ("education", "教育学部"),
                    ("science_engineering", "理工学部"),
                    ("agriculture", "農学部"),
                    ("veterinary", "獣医学部"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("b1", "1年"),
                    ("b2", "2年"),
                    ("b3", "3年"),
                    ("b4", "4年"),
                    ("b5", "5年"),
                    ("b6", "6年"),
                    ("m1", "修士1年"),
                    ("m2", "修士2年"),
                    ("d1", "博士1年"),
                    ("d2", "博士2年"),
                    ("d3", "博士3年"),
                    ("other", "その他"),
                ],
                max_length=10,
            ),
        ),
    ]
